name: gap
description: Flutter widgets for easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views.
version: 1.2.0
homepage: https://github.com/letsar/gap

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

